#!/usr/bin/env node
const sequential = require('promise-sequential')
const odata = require('odata-client')
const utils = require('./utils.js')

// setup odata source to read customers from
const odataService = odata({
    'service': 'http://services.odata.org/V3/Northwind/Northwind.svc', 
    'resources': 'Customers',
    'format': 'json'
})

// ensure command line arguments, that the org is empty and then import data
utils.ensureCommandLineArguments().then(options => utils.ensureOrgData(options, odataService)).then(responses => {
    const sfconn = responses[0]
    const odata = responses[1]

    return sequential(odata.map(c => {
        // map data into Salesforce SObject
        let obj = {
            'Name': c.CompanyName,
            'Fax': c.Fax, 'Phone': c.Phone,
            'BillingStreet': c.Address, 'BillingCity': c.City, 'BillingPostalCode': c.PostalCode, 'BillingCountry': c.Country,
            'Type': 'Customer - Channel',
            'Website': `https://www.example.com`,
            'Site': c.Country,
            'Industry': 'Retail',
            'AccountNumber': c.CustomerID,
            'SAP_Customer_ID__c': c.CustomerID,
            'Rating': c.Rating
        }
        
        // do insert
        return () => {
            return sfconn.insert('Account', obj)
        }
    }))
}).then(() => {
    console.log("Done!")
}).catch(err => {
    console.log(err)
})
